---
- name: Update pkgin cache.
  shell: pkgin update -f

- name: Ensure nginx is installed.
  pkgin:
    name: "{{ nginx_package_name }}"
    state: present

- name: Create logs directory.
  file:
    path: /var/log/nginx
    state: directory
